apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-web
spec:
  storageClassName: standard-rwo
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: drupal-web
    namespace: portal
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/{{ .Values.project }}/zones/{{ .Values.zone }}/disks/{{ .Values.disk }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: topology.gke.io/zone
            operator: In
            values:
            - {{ .Values.zone }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-web
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo