apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/app-protocols: '{"https":"HTTPS"}'
    cloud.google.com/backend-config: '{"ports": {
      "https":"{{ .Chart.Name }}-healthcheck"
    }}'
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
  ports:
    - name: https
      protocol: TCP
      port: {{ .Values.services.nginx.port }}
      targetPort: {{ .Values.services.nginx.port }}
